dashboard:
	docker exec postgres-data pg_dump -U postgres -d dashboard > dashboard-demo.sql

dashboard-manager:
	docker exec postgres-manager pg_dump -U postgres -d dashboardmanager > dashboardmanager-demo.sql