{{- if and .Values.backend.enabled (hasKey .Values.backend "pdb") (hasKey .Values.backend.pdb "enabled") .Values.backend.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "taipei-city-dashboard.fullname" . }}-backend-pdb
  labels:
    {{- include "taipei-city-dashboard.backend.labels" . | nindent 4 }}
spec:
  {{- if and (hasKey .Values.backend.pdb "minAvailable") .Values.backend.pdb.minAvailable }}
  minAvailable: {{ .Values.backend.pdb.minAvailable }}
  {{- else if and (hasKey .Values.backend.pdb "maxUnavailable") .Values.backend.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.backend.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "taipei-city-dashboard.backend.selectorLabels" . | nindent 6 }}
{{- end }}
