{{- if and .Values.frontend.enabled .Values.frontend.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "taipei-city-dashboard.fullname" . }}-frontend-pdb
  labels:
    {{- include "taipei-city-dashboard.frontend.labels" . | nindent 4 }}
spec:
  {{- if .Values.frontend.pdb.minAvailable }}
  minAvailable: {{ .Values.frontend.pdb.minAvailable }}
  {{- else if .Values.frontend.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.frontend.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "taipei-city-dashboard.frontend.selectorLabels" . | nindent 6 }}
{{- end }}
