{{- if and .Values.frontend.enabled .Values.frontend.nginx.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "taipei-city-dashboard.fullname" . }}-frontend-nginx
  labels:
    {{- include "taipei-city-dashboard.frontend.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen {{ default .Values.frontend.service.targetPort .Values.frontend.nginx.configMap.listenPort }};
        server_name {{ default "_" .Values.frontend.nginx.configMap.serverName }};
        root /usr/share/nginx/html;
        index index.html;

        access_log /dev/stdout;
        error_log /dev/stderr warn;

        location /nominatim/ {
            proxy_pass https://nominatim.openstreetmap.org/;
            proxy_http_version 1.1;
            proxy_ssl_server_name on;
            proxy_set_header Host nominatim.openstreetmap.org;
            proxy_set_header User-Agent "Taipei-City-Dashboard/2.2";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Connection "";
            proxy_buffering off;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
{{- end }}
