{{- if .Values.azureKeyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "taipei-city-dashboard.secretProviderClassName" . }}
  labels:
    {{- include "taipei-city-dashboard.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.azureKeyVault.clientId | quote }}
    keyvaultName: {{ .Values.azureKeyVault.vaultName | quote }}
    cloudName: ""
    objects: |
      array:
        {{- if .Values.frontend.enabled }}
        {{- range .Values.frontend.secretEnv }}
        - |
          objectName: {{ .secretKey | quote }}
          objectType: secret
          objectVersion: ""
        {{- end }}
        {{- end }}
        {{- if .Values.backend.enabled }}
        {{- range .Values.backend.secretEnv }}
        - |
          objectName: {{ .secretKey | quote }}
          objectType: secret
          objectVersion: ""
        {{- end }}
        {{- end }}
    tenantId: {{ .Values.azureKeyVault.tenantId | quote }}
  secretObjects:
    - secretName: {{ include "taipei-city-dashboard.fullname" . }}-secrets
      type: Opaque
      data:
        {{- if .Values.frontend.enabled }}
        {{- range .Values.frontend.secretEnv }}
        - objectName: {{ .secretKey | quote }}
          key: {{ .name | quote }}
        {{- end }}
        {{- end }}
        {{- if .Values.backend.enabled }}
        {{- range .Values.backend.secretEnv }}
        - objectName: {{ .secretKey | quote }}
          key: {{ .name | quote }}
        {{- end }}
        {{- end }}
{{- end }}
